# Copyright 2022 Undistro Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

{{ if .Values.saas.workspaceID }}
apiVersion: v1
kind: Pod
metadata:
  name: "{{ include "zora.fullname" . }}-install-hook"
  labels:
    {{- include "zora.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  automountServiceAccountToken: false
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
    runAsGroup: 1000
  containers:
    - name: curl
      image: {{ .Values.hooks.install.image.repository }}:{{ .Values.hooks.install.image.tag }}
      command:
        - sh
        - -xc
        - |
          curl -kfsS -X POST '{{ tpl .Values.saas.installURL . }}' \
            -H 'content-type: application/json' \
          {{- if .Values.httpsProxy }}
            -x '{{ .Values.httpsProxy}}' \
          {{- end }}
            -d '{{ toJson (dict
              "kubeVersion" .Capabilities.KubeVersion.GitVersion
              "chartVersion" .Chart.Version
              "appVersion" .Chart.AppVersion
              "release" .Release.Name
              "namespace" .Release.Namespace
              "revision" .Release.Revision) }}'
      securityContext:
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: true
  restartPolicy: Never
{{- end }}
