ui:
  image:
    tag: saas-0.4.1
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 50m
      memory: 100Mi
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 20
    targetCPUUtilizationPercentage: 60
    targetMemoryUtilizationPercentage: 60
ingress:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production-http01
  enabled: true
  className: nginx
  host: zora-dashboard.undistro.io
  tlsSecretName: zora-saas-cert
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 100Mi
imagePullSecrets:
  - name: zora-saas-registry-cred
storage: "mongo"
mongo:
  database: "zora-saas-prod"
log:
  level: info
proxy:
  enabled: false
monitor:
  enabled: true
autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 20
  targetCPUUtilizationPercentage: 60
  targetMemoryUtilizationPercentage: 60
