ingress:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/proxy-buffer-size: 32k
    nginx.ingress.kubernetes.io/proxy-buffering: "on"
    nginx.ingress.kubernetes.io/proxy-buffers: 8 32k
    nginx.ingress.kubernetes.io/proxy-busy-buffer-size: 32k
  enabled: true
  className: nginx
  host: saas-dev.undistro.io
  tlsSecretName: zora-saas-cert
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 2m
    memory: 15Mi
imagePullSecrets:
  - name: zora-saas-registry-cred
log:
  level: debug
readTimeout: "30s"
writeTimeout: "60s"
grafanaDashboard:
  enabled: false
blockNewUsers: false
