ui:
  image:
    tag: saas-0.9.2
  resources:
    limits:
      #cpu: 100m
      memory: 384Mi
    requests:
      cpu: 100m
      memory: 200Mi
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 20
    targetCPUUtilizationPercentage: 60
    targetMemoryUtilizationPercentage: 60
ingress:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production-http01
    nginx.ingress.kubernetes.io/proxy-body-size: 500m
  enabled: true
  className: nginx
  host: zora-dashboard.undistro.io
  tlsSecretName: zora-saas-cert
resources:
  limits:
    cpu: 200m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 200Mi
imagePullSecrets:
  - name: zora-saas-registry-cred
mongo:
  database: "zora-saas-prod"
log:
  level: debug
readTimeout: "30s"
writeTimeout: "60s"
proxy:
  enabled: false
monitor:
  enabled: true
autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 20
  targetCPUUtilizationPercentage: 60
  targetMemoryUtilizationPercentage: 60
blockNewUsers: true
