{{- if and .Values.admin.enabled .Values.admin.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "zora-saas.fullname" . }}-admin
  labels:
    {{- include "zora-saas.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "zora-saas.fullname" . }}-admin
  minReplicas: {{ .Values.admin.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.admin.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.admin.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.admin.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.admin.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.admin.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}
