{
 "title": "Zora / Monitoring",
 "tags": [ "zora" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Running Pods",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(namespace_workload_pod:kube_pod_owner:relabel{namespace=\"zora-saas\", workload_type=\"deployment\"}) by (workload, workload_type)",
     "legendFormat": "{{workload}}"
    }
   ]
  },
  {
   "title": "Ingress (zora-saas) Request Volume",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "round(sum(irate(nginx_ingress_controller_requests{ingress=~\"zora-saas\"}[2m])) by (ingress), 0.001)",
     "legendFormat": "{{ingress}}"
    }
   ]
  },
  {
   "title": "Request Duration",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99,sum(irate(zora_request_duration_seconds_bucket[1m])) by (le))",
     "legendFormat": "P99"
    },
    {
     "expr": "histogram_quantile(0.90,sum(irate(zora_request_duration_seconds_bucket[1m])) by (le))",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(0.50,sum(irate(zora_request_duration_seconds_bucket[1m])) by (le))",
     "legendFormat": "P50"
    }
   ]
  },
  {
   "title": "Error Rate (4|5xx responses)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "sum(increase(zora_requests_total{status=~\"^[4-5].*\"}[5m])) by (status, method, path)",
     "legendFormat": "{{method}} {{path}} - {{status}}"
    }
   ]
  },
  {
   "title": "Success Rate (non-4|5xx responses)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(zora_requests_total{status!~\"^[4-5].*\"}[2m])) / sum(rate(zora_requests_total[2m]))"
    }
   ]
  },
  {
   "title": "Success Rate (non-4|5xx responses)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 18, "x": 6, "y": 14 },
   "targets": [
    {
     "expr": "sum(increase(zora_requests_total{status!~\"^[4-5].*\"}[5m])) by (status, method, path)",
     "legendFormat": "{{method}} {{path}} - {{status}}"
    }
   ]
  }
 ]
}