{{- if .Values.proxy.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: saas-proxy-client
  labels:
    {{- include "zora-saas.labels" . | nindent 4 }}
rules:
  - nonResourceURLs:
    {{- range $e := .Values.proxy.endpoints }}
      - "{{ $e }}"
    {{- end }}
    verbs: 
    {{- range $v := .Values.proxy.verbs }}
      - "{{ $v }}"
    {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: saas-proxy-client
  labels:
    {{- include "zora-saas.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: saas-proxy-client
subjects:
  - kind: ServiceAccount
    name: saas-proxy-client
    namespace: {{ .Release.Namespace }}
{{- end }}
