{{- if .Values.grafanaDashboard.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "zora-saas.fullname" . }}-dashboards
  namespace: {{ .Values.grafanaDashboard.namespace }}
  labels:
    grafana_dashboard: "1"
    {{- include "zora-saas.labels" . | nindent 4 }}
data:
{{ (.Files.Glob "dashboards/*").AsConfig | indent 2 }}
{{- end }}
