# Copyright 2022 Undistro Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "zora.fullname" . }}-operator
  labels:
    {{- include "zora.operatorLabels" . | nindent 4 }}
spec:
  replicas: {{ .Values.operator.replicaCount }}
  selector:
    matchLabels:
      {{- include "zora.operatorSelectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.operator.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "zora.operatorSelectorLabels" . | nindent 8 }}
    spec:
      {{- if .Values.imageCredentials.create  }}
      imagePullSecrets:
        - name: {{ include "zora.fullname" . }}-registry-cred
      {{- else if not (eq (len .Values.imagePullSecrets) 0) }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- end }}
      containers:
        - name: kube-rbac-proxy
          args:
            - --secure-listen-address=0.0.0.0:8443
            - --upstream=http://127.0.0.1:8080/
            - --logtostderr=true
            - --v=0
          image: "{{ .Values.operator.rbacProxy.image.repository }}:{{ .Values.operator.rbacProxy.image.tag }}"
          imagePullPolicy: {{ .Values.operator.rbacProxy.image.pullPolicy }}
          ports:
            - containerPort: 8443
              name: https
              protocol: TCP
          resources:
            {{- toYaml .Values.operator.rbacProxy.resources | nindent 12 }}
          securityContext:
            {{- toYaml .Values.operator.rbacProxy.securityContext | nindent 12 }}
        - name: manager
          {{- if .Values.httpsProxy }}
          env:
            - name: HTTPS_PROXY
              value: {{ .Values.httpsProxy | quote }}
            - name: NO_PROXY
              value: {{ .Values.noProxy | quote }}
          {{- end }}
          command:
            - /manager
          args:
            - --health-probe-bind-address=:8081
            - --metrics-bind-address=127.0.0.1:8080
            - --leader-elect
            - --zap-encoder={{ .Values.operator.log.encoding }}
            - --zap-log-level={{ .Values.operator.log.level }}
            - --zap-stacktrace-level={{ .Values.operator.log.stacktraceLevel }}
            - --zap-time-encoding={{ .Values.operator.log.timeEncoding }}
            - --default-plugins-namespace={{ .Release.Namespace }}
            - --default-plugins-names={{ join "," .Values.scan.misconfiguration.plugins }}
            - --worker-image={{ printf "%s:%s" .Values.scan.worker.image.repository (.Values.scan.worker.image.tag | default .Chart.AppVersion) }}
            - --cronjob-clusterrolebinding-name=zora-plugins-rolebinding
            - --cronjob-serviceaccount-name=zora-plugins
            - --trivy-db-pvc={{- if .Values.scan.plugins.trivy.persistence.enabled }}trivy-db{{- end }}
{{- if .Values.scan.plugins.annotations}}
            - --cronjob-serviceaccount-annotations={{ $first := true }}{{- range $key, $value := .Values.scan.plugins.annotations }}{{if not $first}},{{else}}{{$first = false}}{{end}}{{ $key }}={{$value}}{{- end }}
{{- end }}
            - --saas-workspace-id={{ .Values.saas.workspaceID }}
            - --saas-server={{ .Values.saas.server }}
            - --version={{ .Chart.Version }}
            - --checks-configmap-namespace={{ .Release.Namespace }}
            - --checks-configmap-name={{ .Values.customChecksConfigMap }}
            - --kubexns-image={{ printf "%s:%s" .Values.kubexnsImage.repository .Values.kubexnsImage.tag }}
            - --update-crds={{ .Values.updateCRDs | default .Release.IsUpgrade }}
          image: "{{ .Values.operator.image.repository }}:{{ .Values.operator.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.operator.image.pullPolicy }}
          ports:
            - containerPort: 8081
              protocol: TCP
              name: probe
            - containerPort: 8080
              protocol: TCP
              name: metrics
          livenessProbe:
            httpGet:
              path: /healthz
              port: probe
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: probe
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            {{- toYaml .Values.operator.resources | nindent 12 }}
          securityContext:
            {{- toYaml .Values.operator.securityContext | nindent 12 }}
      securityContext:
        {{- toYaml .Values.operator.podSecurityContext | nindent 8 }}
      serviceAccountName: {{ include "zora.operatorServiceAccountName" . }}
      terminationGracePeriodSeconds: 10
      {{- with .Values.operator.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.operator.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.operator.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
